### ISSUE TITLE
Tried to load unspecified class: Alexandria::Library

### ISSUE THREAD

**Issue by dodona2** [mvz/alexandria-book-collection-manager#130]
```
(0/1)~/tmp/hwgtkmm3/trunk$ alexandria 
-----------------------
Alexandria just crashed
-----------------------
Timestamp: 2021-02-24 16:55:27 +0100
Message: Tried to load unspecified class: Alexandria::Library
Backtrace:
/usr/share/ruby/psych/class_loader.rb:97:in `find'
/usr/share/ruby/psych/class_loader.rb:28:in `load'
/usr/share/ruby/psych/visitors/to_ruby.rb:411:in `resolve_class'
/usr/share/ruby/psych/visitors/to_ruby.rb:149:in `visit_Psych_Nodes_Sequence'
/usr/share/ruby/psych/visitors/visitor.rb:16:in `visit'
/usr/share/ruby/psych/visitors/visitor.rb:6:in `accept'
/usr/share/ruby/psych/visitors/to_ruby.rb:32:in `accept'
/usr/share/ruby/psych/visitors/to_ruby.rb:340:in `block in revive_hash'
/usr/share/ruby/psych/visitors/to_ruby.rb:338:in `each'
/usr/share/ruby/psych/visitors/to_ruby.rb:338:in `each_slice'
/usr/share/ruby/psych/visitors/to_ruby.rb:338:in `revive_hash'
/usr/share/ruby/psych/visitors/to_ruby.rb:394:in `revive'
/usr/share/ruby/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
/usr/share/ruby/psych/visitors/visitor.rb:16:in `visit'
/usr/share/ruby/psych/visitors/visitor.rb:6:in `accept'
/usr/share/ruby/psych/visitors/to_ruby.rb:32:in `accept'
/usr/share/ruby/psych/visitors/to_ruby.rb:313:in `visit_Psych_Nodes_Document'
/usr/share/ruby/psych/visitors/visitor.rb:16:in `visit'
/usr/share/ruby/psych/visitors/visitor.rb:6:in `accept'
/usr/share/ruby/psych/visitors/to_ruby.rb:32:in `accept'
/usr/share/ruby/psych.rb:360:in `safe_load'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:223:in `regularize_book_from_yaml'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:60:in `block (2 levels) in load_library'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:48:in `each'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:48:in `block in load_library'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:47:in `chdir'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:47:in `load_library'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:30:in `block in load_all_libraries'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:24:in `each'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:24:in `load_all_libraries'
/usr/share/ruby/vendor_ruby/alexandria/library_collection.rb:20:in `reload'
/usr/share/ruby/vendor_ruby/alexandria/ui/ui_manager.rb:604:in `load_libraries'
/usr/share/ruby/vendor_ruby/alexandria/ui/ui_manager.rb:33:in `initialize'
/usr/share/ruby/vendor_ruby/alexandria/ui/main_app.rb:57:in `new'
/usr/share/ruby/vendor_ruby/alexandria/ui/main_app.rb:57:in `initialize'
/usr/share/ruby/singleton.rb:125:in `new'
/usr/share/ruby/singleton.rb:125:in `block in instance'
/usr/share/ruby/singleton.rb:123:in `synchronize'
/usr/share/ruby/singleton.rb:123:in `instance'
/usr/share/ruby/vendor_ruby/alexandria/ui.rb:42:in `start_main_app'
/usr/share/ruby/vendor_ruby/alexandria/ui.rb:54:in `main'
/usr/share/ruby/vendor_ruby/alexandria.rb:38:in `main'
/usr/bin/alexandria:37:in `<main>'
Release: 0.7.8(0.7.8)
Uname -a: Linux MYLBOX 5.10.16-200.fc33.x86_64 #1 SMP Sun Feb 14 03:02:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
--
Please report this dump to 'http://www.github.com/mvz/alexandria-book-collection-manager/issues' with some additional
information, such as the description of the crash and the steps to reproduce it
(if it's possible).
```

**Comment by mvz** [comment]
Thanks @dodona2, this will be fixed in the next release.
