### ISSUE TITLE
alexandria won't launch when position has negative value

### ISSUE THREAD

**Issue by mtasaka** [mvz/alexandria-book-collection-manager#135]
Original downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1014295

Reproducer: (with Fedora alexandria-0.7.8-1.fc33 with relevant patch removed)

* once launch alexandria
* move alexandria GUI window to left so that alexandria GUI window protrudes from the window
* Ctrl-q to once quit alexandria
* check `gconftool-2 --recursive-list /apps/alexandria | grep position` and it shows something like `position = (-242,248)`
* again launch alexandria

Then alexandria won't launch like (line number may differ)
```
-----------------------
Alexandria just crashed
-----------------------
Timestamp: 2021-03-13 23:22:48 +0900
Message: no implicit conversion of String into Integer
Backtrace:
/usr/share/gems/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:600:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:600:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:514:in `block in define_method'
/home/mtasaka/rpmbuild/fedora-specific/alexandria/f34/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb:1042:in `restore_preferences'
/home/mtasaka/rpmbuild/fedora-specific/alexandria/f34/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb:48:in `initialize'
/home/mtasaka/rpmbuild/fedora-specific/alexandria/f34/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/main_app.rb:57:in `new'
/home/mtasaka/rpmbuild/fedora-specific/alexandria/f34/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/main_app.rb:57:in `initialize'
/usr/share/ruby/singleton.rb:125:in `new'
/usr/share/ruby/singleton.rb:125:in `block in instance'
/usr/share/ruby/singleton.rb:123:in `synchronize'
/usr/share/ruby/singleton.rb:123:in `instance'
/home/mtasaka/rpmbuild/fedora-specific/alexandria/f34/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui.rb:42:in `start_main_app'
/home/mtasaka/rpmbuild/fedora-specific/alexandria/f34/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui.rb:54:in `main'
/home/mtasaka/rpmbuild/fedora-specific/alexandria/f34/alexandria-book-collection-manager-0.7.8/lib/alexandria.rb:38:in `main'
/bin/alexandria:37:in `<main>'
Release: 0.7.8(0.7.8)
Uname -a: Linux localhost.localdomain 5.10.11-200.fc33.x86_64 #1 SMP Wed Jan 27 20:21:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
--
Please report this dump to 'http://www.github.com/mvz/alexandria-book-collection-manager/issues' with some additional
information, such as the description of the crash and the steps to reproduce it
(if it's possible).
```

Ref:
https://src.fedoraproject.org/rpms/alexandria/blob/dc5c9f459aa72bd71628e8bf695f9c82c1c59ff0/f/alexandria-0.7.6-negative-value.patch

**Comment by mvz** [comment]
Thanks, @mtasaka!
