### ISSUE TITLE
Unable to use or import older database

### ISSUE THREAD

**Issue by jmb365** [mvz/alexandria-book-collection-manager#160]
I recently upgrade to Ubuntu 20.04 and installed:
  'gem install alexandria-book-collection-manager'

Next I tried to use the ~/.alexandria sub-folder from a much older version 0.6.3.  The new version 0.7.8 crashes with a series of error messages.  Next I renamed the ~/.alexandria sub-folder, so that I could create a clean database and try to import each *.yaml file from the older sub-folder.  This too crashes it.  Are there any workarounds, fixes or tricks?  Am I out of luck trying to use an older database, in which case I would be very disappointed.  Do you need a detailed log of the error messages to provide advice?  Thank you for any replies.

**Comment by mvz** [comment]
Hi @jmb365, the data format of version 0.6.3 should be compatible with the current version.

Please do send a detailed log of error messages so I can see what's going on.

**Comment by jmb365** [comment]
Hello @mvz,

Thank you for your reply!  The attached text shows the error message when pointed to the older database.  If you need any other information do let me know.  I appreciate your help.

-----------------------
Alexandria just crashed
-----------------------
Timestamp: 2021-09-27 13:20:53 -0400
Message: Tried to load unspecified class: Alexandria::Library
Backtrace:
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/class_loader.rb:97:in `find'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/class_loader.rb:28:in `load'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:422:in `resolve_class'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:153:in `visit_Psych_Nodes_Sequence'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:16:in `visit'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:6:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:34:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:341:in `each'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:341:in `each_slice'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:341:in `revive_hash'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:405:in `revive'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:212:in `visit_Psych_Nodes_Mapping'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:16:in `visit'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:6:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:34:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:317:in `visit_Psych_Nodes_Document'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:16:in `visit'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:6:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:34:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych.rb:361:in `safe_load'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:206:in `regularize_book_from_yaml'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:63:in `block (2 levels) in load_library'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:48:in `each'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:48:in `block in load_library'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:47:in `chdir'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:47:in `load_library'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:30:in `block in load_all_libraries'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:24:in `each'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:24:in `load_all_libraries'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_collection.rb:20:in `reload'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb:604:in `load_libraries'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb:33:in `initialize'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/main_app.rb:57:in `new'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/main_app.rb:57:in `initialize'
/usr/lib/ruby/2.7.0/singleton.rb:125:in `new'
/usr/lib/ruby/2.7.0/singleton.rb:125:in `block in instance'
/usr/lib/ruby/2.7.0/singleton.rb:123:in `synchronize'
/usr/lib/ruby/2.7.0/singleton.rb:123:in `instance'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui.rb:42:in `start_main_app'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui.rb:54:in `main'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria.rb:38:in `main'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/bin/alexandria:37:in `<top (required)>'
/usr/local/bin/alexandria:23:in `load'
/usr/local/bin/alexandria:23:in `<main>'
Release: 0.7.8(0.7.8)
Uname -a: Linux ubuntu52 5.8.0-492104061620-generic SMP Fri Apr 16 14:14:47 UTC 20 x86_64 x86_64 x86_64 GNU/Linux
--
Please report this dump to 'http://www.github.com/mvz/alexandria-book-collection-manager/issues' with some additional
information, such as the description of the crash and the steps to reproduce it
(if it's possible).

[1]+  Exit 1                  /usr/local/bin/alexandria

**Comment by mvz** [comment]
Thanks, @jmb365, that's very helpful.

I'm repeating the contents below for later reference:

```
-----------------------
Alexandria just crashed
-----------------------
Timestamp: 2021-09-27 13:20:53 -0400
Message: Tried to load unspecified class: Alexandria::Library
Backtrace:
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/class_loader.rb:97:in `find'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/class_loader.rb:28:in `load'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:422:in `resolve_class'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:153:in `visit_Psych_Nodes_Sequence'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:16:in `visit'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:6:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:34:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:343:in `block in revive_hash'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:341:in `each'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:341:in `each_slice'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:341:in `revive_hash'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:405:in `revive'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:212:in `visit_Psych_Nodes_Mapping'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:16:in `visit'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:6:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:34:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:317:in `visit_Psych_Nodes_Document'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:16:in `visit'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/visitor.rb:6:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych/visitors/to_ruby.rb:34:in `accept'
/var/lib/gems/2.7.0/gems/psych-3.2.1/lib/psych.rb:361:in `safe_load'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:206:in `regularize_book_from_yaml'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:63:in `block (2 levels) in load_library'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:48:in `each'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:48:in `block in load_library'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:47:in `chdir'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:47:in `load_library'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:30:in `block in load_all_libraries'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:24:in `each'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_store.rb:24:in `load_all_libraries'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/library_collection.rb:20:in `reload'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb:604:in `load_libraries'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb:33:in `initialize'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/main_app.rb:57:in `new'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/main_app.rb:57:in `initialize'
/usr/lib/ruby/2.7.0/singleton.rb:125:in `new'
/usr/lib/ruby/2.7.0/singleton.rb:125:in `block in instance'
/usr/lib/ruby/2.7.0/singleton.rb:123:in `synchronize'
/usr/lib/ruby/2.7.0/singleton.rb:123:in `instance'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui.rb:42:in `start_main_app'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria/ui.rb:54:in `main'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/lib/alexandria.rb:38:in `main'
/var/lib/gems/2.7.0/gems/alexandria-book-collection-manager-0.7.8/bin/alexandria:37:in `<top (required)>'
/usr/local/bin/alexandria:23:in `load'
/usr/local/bin/alexandria:23:in `<main>'
Release: 0.7.8(0.7.8)
Uname -a: Linux ubuntu52 5.8.0-492104061620-generic SMP Fri Apr 16 14:14:47 UTC 20 x86_64 x86_64 x86_64 GNU/Linux
--
Please report this dump to 'http://www.github.com/mvz/alexandria-book-collection-manager/issues' with some additional
information, such as the description of the crash and the steps to reproduce it
(if it's possible).

[1]+  Exit 1                  /usr/local/bin/alexandria
```

**Comment by jmb365** [comment]
Hello @ mvz,

Happy New Year!  Any news or progress regarding the bug fix?

Thanks!
JMB
