### ISSUE TITLE
Just crash at the sturtup on Fedora 41

### ISSUE THREAD

**Issue by thekurtz** [mvz/alexandria-book-collection-manager#263]
The following dump is produced by starting Alexandria from terminal on an update Fedora 41 OS.  I used the software a couple of time and was starting even if showing some problems in windows dimensions, it crashed after clicking to open a book recenly added. After a couple of crashes like that it just stopped to startup. Now lunching from terminal I get:
```

-----------------------
Alexandria just crashed
-----------------------
Timestamp: 2024-11-14 14:48:16 +0100
Message: uninitialized constant Syck::UNESCAPES
Backtrace:
/usr/share/gems/gems/syck-1.5.1.1/lib/syck/encoding.rb:30:in `block in unescape'
/usr/share/gems/gems/syck-1.5.1.1/lib/syck/encoding.rb:24:in `gsub'
/usr/share/gems/gems/syck-1.5.1.1/lib/syck/encoding.rb:24:in `unescape'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:222:in `regularize_book_from_yaml'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:60:in `block (2 levels) in load_library'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:48:in `each'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:48:in `block in load_library'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:47:in `chdir'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:47:in `load_library'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:30:in `block in load_all_libraries'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:24:in `each'
/usr/share/ruby/vendor_ruby/alexandria/library_store.rb:24:in `load_all_libraries'
/usr/share/ruby/vendor_ruby/alexandria/library_collection.rb:20:in `reload'
/usr/share/ruby/vendor_ruby/alexandria/ui/ui_manager.rb:604:in `load_libraries'
/usr/share/ruby/vendor_ruby/alexandria/ui/ui_manager.rb:33:in `initialize'
/usr/share/ruby/vendor_ruby/alexandria/ui/main_app.rb:57:in `new'
/usr/share/ruby/vendor_ruby/alexandria/ui/main_app.rb:57:in `initialize'
/usr/share/ruby/singleton.rb:124:in `new'
/usr/share/ruby/singleton.rb:124:in `block in instance'
/usr/share/ruby/singleton.rb:124:in `synchronize'
/usr/share/ruby/singleton.rb:124:in `instance'
/usr/share/ruby/vendor_ruby/alexandria/ui.rb:42:in `start_main_app'
/usr/share/ruby/vendor_ruby/alexandria/ui.rb:54:in `main'
/usr/share/ruby/vendor_ruby/alexandria.rb:38:in `main'
/usr/bin/alexandria:37:in `<main>'
Release: 0.7.9(0.7.9)
Uname -a: Linux AAAAA-lap 6.11.6-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov  1 16:16:00 UTC 2024 x86_64 GNU/Linux
--

```

**Comment by mvz** [comment]
Hi @thekurtz, it looks like the problem is in a patch that Fedora applies: https://src.fedoraproject.org/rpms/alexandria/blob/rawhide/f/alexandria-0.7.9-yaml-unescape.patch.

Can you please open an issue with Fedora for this?

**Comment by thekurtz** [comment]
Thankyou, done:
https://bugzilla.redhat.com/show_bug.cgi?id=2326632

**Comment by mvz** [comment]
It looks like a fix was released in Fedora, so I'll close this.
