### ISSUE TITLE
Crash searching for book via ISBN

### ISSUE THREAD

**Issue by vuyibiran** [mvz/alexandria-book-collection-manager#3]
Hello

I did intall alexandria via gem on debian sid.

If I start a search via an ISBN number alexandria crashes.

Crashlog:

```
$ alexandria 
{}
"{}"
3833936517
9783833936517
/var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/dialogs/new_book_dialog.rb:566:in `block in update': undefined method `status=' for #<Gtk::Statusbar:0x399ae50 ptr=0x3976040>
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:72:in `call'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:72:in `block (3 levels) in main_with_queue'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:71:in `each'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:71:in `block (2 levels) in main_with_queue'
	 from /usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:70:in `block in main_with_queue'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:78:in `call'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:78:in `main'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui/gtk_thread_help.rb:78:in `main_with_queue'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui.rb:45:in `start_gtk'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria/ui.rb:50:in `main'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/lib/alexandria.rb:50:in `main'
	 from /var/lib/gems/2.2.0/gems/alexandria-book-collection-manager-0.6.9/bin/alexandria:64:in `<top (required)>'
	 from /usr/local/bin/alexandria:23:in `load'
	 from /usr/local/bin/alexandria:23:in `<main>'
```

**Comment by mvz** [comment]
Thanks for your report, @vuyibiran. I'll look into it.

**Comment by mvz** [comment]
This particular crash is fixed in master, but on my machine the book search then crashes later on somewhere inside the gtk2 gem.

**Comment by mvz** [comment]
No crashes occur anymore when adding a book via ISBN.
