### ISSUE TITLE
Alexandria crash when i try to create a new library

### ISSUE THREAD

**Issue by jbriard** [mvz/alexandria-book-collection-manager#68]
Hi,

I'm using alexandria v: 0.7.5
I'm on Fedora 32

The application crash when I try to create a new library :

```
+1: /home/bob/.gem/ruby/gems/alexandria-book-collection-manager-0.7.5/lib/alexandria/ui/callbacks.rb:16:in `on_new': private method `load' called for Alexandria::Library:Class
	 from /usr/share/gems/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:598:in `invoke'
	 from /usr/share/gems/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:598:in `invoke'
	 from /usr/share/gems/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:103:in `block in define_singleton_method'
	 from /home/bob/.gem/ruby/gems/alexandria-book-collection-manager-0.7.5/lib/alexandria/ui.rb:49:in `start_gtk'
	 from /home/bob/.gem/ruby/gems/alexandria-book-collection-manager-0.7.5/lib/alexandria/ui.rb:55:in `main'
	 from /home/bob/.gem/ruby/gems/alexandria-book-collection-manager-0.7.5/lib/alexandria.rb:38:in `main'
	 from /home/bob/.gem/ruby/gems/alexandria-book-collection-manager-0.7.5/bin/alexandria:37:in `<top (required)>'
	 from /home/bob/bin/alexandria:23:in `load'
	 from /home/bob/bin/alexandria:23:in `<main>'
/home/bob/bin/alexandria: [BUG] Segmentation fault at 0x000055fb0000009a
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0001 p:0000 s:0003 E:000060 (none) [FINISH]


-- Machine register context ------------------------------------------------
 RIP: 0x00007f428246f89c RBP: 0x000055fb1bd56ee0 RSP: 0x00007ffcd8b0b310
 RAX: 0x000055fb00000092 RBX: 0x00007ffcd8b0b5b0 RCX: 0x00000000000000a3
 RDX: 0x000055fb1d1f47d0 RDI: 0x00007f42824a12c0 RSI: 0x0000000000000000
  R8: 0x00007ffcd8b0b430  R9: 0x0000000000000003 R10: 0x0000000000000001
 R11: 0x0000000000000140 R12: 0x000055fb1bd56ee0 R13: 0x00007f428248e188
 R14: 0x00007ffcd8b0b520 R15: 0x0000000000000000 EFL: 0x0000000000010202

-- Other runtime information -----------------------------------------------

* Loaded script: /home/bob/bin/alexandria
```

I put the log here https://bin.idrix.fr/?527869bfee89cff4#3GjoahuDhWekRMruYQsAX4jjwiBF8oqcu2HYJnt2S9Dj

**Comment by mvz** [comment]
Hi @jbriard I have just released version 0.7.6 which fixes this issue.
